export {
  createDocumentCore,
  DocumentCoreError,
  DocumentSourceEditError,
  type CommentProjection,
  type CriticMarkupAnnotation,
  type CriticMarkupArm,
  type CriticMarkupKind,
  type DocumentCore,
  type DocumentChange,
  type DocumentCommit,
  type DocumentApplyOptions,
  type DocumentCoreErrorCode,
  type DocumentDiagnostic,
  type DocumentDiagnosticCode,
  type DocumentProjection,
  type DocumentProjectionName,
  type DocumentRevision,
  type DocumentSourceEdit,
  type MarkdownAst,
  type MarkdownAstNode,
  type MarkdownAttribute,
  type MarkdownNodeKind,
  type MarkdownOptions,
  type MarkdownProjection,
  type MarkdownProjectionName,
  type MarkupEvent,
  type MarkupCoordinateSegment,
  type MarkupMark,
  type MarkupProjection,
  type MarkupRegionProjectionChange,
  type MarkupRegionReplacement,
  type MarkupSyntax,
  type OrdinalRange,
  type DocumentProjectionChange,
  type DocumentProjectionFallbackReason,
  type MarkupDocumentProjectionChange,
  type ProjectionAffinity,
  type ProjectionCoordinateMap,
  type ProjectionOrigin,
  type SourceRange
} from './documentCore.js'
