import type {
    TBrandedMappedTextPath,
    TMappedTextPath,
} from '../mapped-range';
import type {
    IMappedTextBoundary,
    IMappedTextNode,
    IMappedTextSpan,
} from '../mappedText';
import { MappedPathIndex, mappedTextPath } from '../mapped-range';
import {
    localOffset,
    MappedText,
    MappedTextWriter,
    sourceOffset,
} from '../mappedText';

export type TMarkdownStatePath
    = TBrandedMappedTextPath<'markdown-state-path'>;

export function markdownStatePath(
    path: readonly (string | number)[],
): TMarkdownStatePath {
    return mappedTextPath<'markdown-state-path'>(path);
}

/** One identity-mapped piece of a formattable leaf's serialized text. */
export interface IMarkdownSourceMapPiece {
    /** Half-open UTF-16 offsets in the live leaf's `text` value. */
    localStart: number;
    localEnd: number;
    /** Half-open UTF-16 offsets in `IMarkdownSourceMap.markdown`. */
    sourceStart: number;
    sourceEnd: number;
}

/** Source pieces for one live/OT text path. */
export interface IMarkdownLeafSourceMap {
    /** The exact JSON-state path used by Content.text, always ending in `text`. */
    path: TMappedTextPath;
    pieces: IMarkdownSourceMapPiece[];
}

/** Canonical Markdown and its piecewise formattable-leaf source map. */
export interface IMarkdownSourceMap {
    markdown: string;
    leaves: IMarkdownLeafSourceMap[];
    nodes?: Array<{
        path: TMappedTextPath;
        sourceStart: number;
        sourceEnd: number;
    }>;
    boundaries?: Array<{
        path: TMappedTextPath;
        localOffset: number;
        sourceOffset: number;
    }>;
}

export type TTrackedMarkdown = MappedText<TMarkdownStatePath>;

export function plainMarkdown(text: string): TTrackedMarkdown {
    return new MappedText<TMarkdownStatePath>(text);
}

/**
 * Replace serializer-generated bytes while retaining every structural node
 * envelope that owned the replaced chunk. Identity-mapped leaf bytes are not
 * replaceable through this path.
 */
export function replaceGeneratedMarkdown(
    generated: TTrackedMarkdown,
    text: string,
): TTrackedMarkdown {
    if (generated.sourceMap.spans.length) {
        throw new TypeError(
            'Generated Markdown replacement cannot discard mapped leaf text.',
        );
    }
    return new MappedText(
        text,
        [],
        generated.sourceMap.nodes.map(node => ({
            path: node.path,
            sourceStart: sourceOffset(0),
            sourceEnd: sourceOffset(text.length),
        })),
    );
}

export function mappedMarkdown(
    text: string,
    path: TMarkdownStatePath,
    start: number,
): TTrackedMarkdown {
    if (!text)
        return plainMarkdown(text);

    return new MappedTextWriter<TMarkdownStatePath>()
        .appendMapped(text, path, localOffset(start))
        .build();
}

export function boundaryMarkdown(
    path: TMarkdownStatePath,
    offset: number,
): TTrackedMarkdown {
    return new MappedTextWriter<TMarkdownStatePath>()
        .appendBoundary(path, localOffset(offset))
        .build();
}

export function concatMarkdown(
    parts: readonly TTrackedMarkdown[],
): TTrackedMarkdown {
    return MappedText.concat(parts);
}

export function sliceMarkdown(
    markdown: TTrackedMarkdown,
    start: number,
    end = markdown.text.length,
): TTrackedMarkdown {
    // Preserve the serializer's established forgiving internal slice contract.
    const normalizedStart = Math.max(0, Math.min(start, markdown.text.length));
    const normalizedEnd = Math.max(
        normalizedStart,
        Math.min(end, markdown.text.length),
    );

    return markdown.slice(
        sourceOffset(normalizedStart),
        sourceOffset(normalizedEnd),
    );
}

/**
 * Slice for source weaving without duplicating nonempty node envelopes as
 * zero-width ranges on both sides of a cut. Identity spans and boundaries keep
 * the ordinary half-open slice behavior; each structural node belongs only to
 * chunks that contain some of its native bytes.
 */
export function sliceMarkdownForWeave(
    markdown: TTrackedMarkdown,
    start: number,
    end = markdown.text.length,
): TTrackedMarkdown {
    const normalizedStart = Math.max(0, Math.min(start, markdown.text.length));
    const normalizedEnd = Math.max(
        normalizedStart,
        Math.min(end, markdown.text.length),
    );
    const sliced = markdown.slice(
        sourceOffset(normalizedStart),
        sourceOffset(normalizedEnd),
    );
    const nodes = markdown.sourceMap.nodes.flatMap((node) => {
        if (node.sourceStart === node.sourceEnd) {
            const ownsEmpty = normalizedStart <= node.sourceStart
                && (
                    node.sourceStart < normalizedEnd
                    || (
                        normalizedEnd === markdown.text.length
                        && node.sourceStart === normalizedEnd
                    )
                );
            return ownsEmpty
                ? [{
                        ...node,
                        sourceStart: sourceOffset(
                            node.sourceStart - normalizedStart,
                        ),
                        sourceEnd: sourceOffset(
                            node.sourceEnd - normalizedStart,
                        ),
                    }]
                : [];
        }
        const clippedStart = Math.max(node.sourceStart, normalizedStart);
        const clippedEnd = Math.min(node.sourceEnd, normalizedEnd);
        return clippedStart < clippedEnd
            ? [{
                    ...node,
                    sourceStart: sourceOffset(
                        clippedStart - normalizedStart,
                    ),
                    sourceEnd: sourceOffset(
                        clippedEnd - normalizedStart,
                    ),
                }]
            : [];
    });
    return new MappedText(
        sliced.text,
        sliced.sourceMap.spans,
        nodes,
        sliced.sourceMap.boundaries,
    );
}

export function removeFirstMarkdown(
    markdown: TTrackedMarkdown,
    search: string,
): TTrackedMarkdown {
    const index = markdown.text.indexOf(search);
    if (index === -1)
        return markdown;

    return concatMarkdown([
        sliceMarkdown(markdown, 0, index),
        sliceMarkdown(markdown, index + search.length),
    ]);
}

/** Adapt the branded internal map to the branch's stable public DTO. */
export function toMarkdownSourceMap<Path extends TMappedTextPath>(
    markdown: MappedText<Path>,
    leafPaths: readonly Path[] = mappedMarkdownLeafPaths(markdown),
): IMarkdownSourceMap {
    const piecesByPath = new MappedPathIndex<Path, IMarkdownSourceMapPiece[]>();
    for (const span of markdown.sourceMap.spans) {
        const pieces = piecesByPath.get(span.path) ?? [];
        pieces.push({
            localStart: span.localStart,
            localEnd: span.localEnd,
            sourceStart: span.sourceStart,
            sourceEnd: span.sourceEnd,
        });
        piecesByPath.set(span.path, pieces);
    }

    return {
        markdown: markdown.text,
        leaves: leafPaths.map(path => ({
            path: [...path],
            pieces: piecesByPath.get(path) ?? [],
        })),
        nodes: markdown.sourceMap.nodes.map(node => ({
            path: [...node.path],
            sourceStart: node.sourceStart,
            sourceEnd: node.sourceEnd,
        })),
        boundaries: markdown.sourceMap.boundaries.map(boundary => ({
            path: [...boundary.path],
            localOffset: boundary.localOffset,
            sourceOffset: boundary.sourceOffset,
        })),
    };
}

/** Distinct mapped leaf paths in their first source-appearance order. */
export function mappedMarkdownLeafPaths<Path extends TMappedTextPath>(
    markdown: MappedText<Path>,
): readonly Path[] {
    const paths = new MappedPathIndex<Path, Path>();
    for (const span of markdown.sourceMap.spans) {
        if (!paths.has(span.path))
            paths.set(span.path, span.path);
    }
    for (const boundary of markdown.sourceMap.boundaries) {
        if (!paths.has(boundary.path))
            paths.set(boundary.path, boundary.path);
    }

    return [...paths.values()];
}

/** Validate the stable public DTO once and enter the branded map domain. */
export function fromMarkdownSourceMap(
    sourceMap: IMarkdownSourceMap,
): TTrackedMarkdown {
    const spans: IMappedTextSpan<TMarkdownStatePath>[] = sourceMap.leaves
        .flatMap(leaf => leaf.pieces.map(piece => ({
            path: markdownStatePath(leaf.path),
            localStart: localOffset(piece.localStart),
            localEnd: localOffset(piece.localEnd),
            sourceStart: sourceOffset(piece.sourceStart),
            sourceEnd: sourceOffset(piece.sourceEnd),
        })))
        .sort((left, right) =>
            left.sourceStart - right.sourceStart
            || left.sourceEnd - right.sourceEnd);
    const nodes: IMappedTextNode<TMarkdownStatePath>[] = (sourceMap.nodes ?? [])
        .map(node => ({
            path: markdownStatePath(node.path),
            sourceStart: sourceOffset(node.sourceStart),
            sourceEnd: sourceOffset(node.sourceEnd),
        }));
    const boundaries: IMappedTextBoundary<TMarkdownStatePath>[]
        = (sourceMap.boundaries ?? []).map(boundary => ({
            path: markdownStatePath(boundary.path),
            localOffset: localOffset(boundary.localOffset),
            sourceOffset: sourceOffset(boundary.sourceOffset),
        }));

    return new MappedText(sourceMap.markdown, spans, nodes, boundaries);
}
